SELECT * FROM customer;

-- Q1.what is the total revenue generated by male vs.female customer
SELECT "Gender", SUM(purchase_amount) AS revenue
FROM customer
GROUP BY "Gender";

-- Q2. which customer used a discount but still spend more than the average purchase amount
SELECT *
FROM customer
WHERE "Discount Applied" = 'Yes'   -- or the value that indicates a discount
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  );

-- Q3. which are the top 5 products with the highest average review rating
SELECT "Item Purchased",
       ROUND(AVG("Review Rating"::numeric), 2) AS avg_rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4. Compare the average purchase amounts between standard and express shipping
SELECT "Shipping Type",
       ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";

-- Q5.do subscribed customer spend more? compare average spend and total revenue
-- between subscribers and non-subscribers

SELECT 
    "Subscription Status",
    COUNT("Customer ID") AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY "Subscription Status"
ORDER BY total_revenue DESC, avg_spend DESC;


-- Q6. which 5 products have the highest percentage of purchase with discount applied
SELECT 
    "Item Purchased",
    ROUND(
        SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)::numeric
        / COUNT(*) * 100, 2
    ) AS discount_percentage
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customer into new returning and loyal based on their totAL
-- number of previous purchases and show the count of each segment
SELECT
    CASE 
        WHEN "Previous Purchases" = 0 THEN 'New'
        WHEN "Previous Purchases" BETWEEN 1 AND 3 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS total_customers
FROM customer
GROUP BY customer_segment
ORDER BY total_customers DESC;

-- Q8. what are the top 3 most purchased products within each category
WITH ranked_products AS (
    SELECT 
        "Category",
        "Item Purchased",
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY "Category" 
            ORDER BY COUNT(*) DESC
        ) AS rank_within_category
    FROM customer
    GROUP BY "Category", "Item Purchased"
)
SELECT "Category", "Item Purchased", total_purchases
FROM ranked_products
WHERE rank_within_category <= 3
ORDER BY "Category", total_purchases DESC;

-- Q9.Are customers whi are repeat buyers (more that 5 previous purchases ) also likely
-- to subscribe

SELECT 
    "Subscription Status",
    COUNT(*) AS total_customers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

-- Q10. what is the revenue contribution of each age group
SELECT 
    CASE 
        WHEN "Age" BETWEEN 18 AND 25 THEN 'Youth Adult'
        WHEN "Age" BETWEEN 26 AND 35 THEN 'Adult'
        WHEN "Age" BETWEEN 36 AND 50 THEN 'Middle-aged'
        ELSE 'Senior'
    END AS age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


